### ISSUE TITLE
Limitations of this library?

### ISSUE THREAD

**Issue by HiImJulien** [mpalazzolo/apple-music-python#4]
Hey there!
Thanks for creating this port :)

I am currently looking for a side project and was wondering whether this library could be used to load audio data for later playback?

Sadly both documentations do not clarify whether this is possible or not. 
The python API documentation, for instance, only says, that the `song` method returns song data. 

What data? Metadata? Audiodata? Both?

**Comment by mpalazzolo** [comment]
Hey,

Currently I only have endpoints built out for catalog resources. The `song` method will return song metadata shown here:
https://developer.apple.com/documentation/applemusicapi/get_a_catalog_song

No audio data is returned, but it includes links and IDs you can use to for a web app or something like that.
