### ISSUE TITLE
Getting Resources for a Genre?

### ISSUE THREAD

**Issue by chigkim** [mpalazzolo/apple-music-python#5]
Is that possible to get different resources such as playlists, new release albums, artists for a specific genre?

**Comment by mpalazzolo** [comment]
I don't think that is currently possible, but I may be wrong. Take a look here : [](https://developer.apple.com/documentation/applemusicapi/). If there is a new endpoint for catalog resources under the genre section that I am missing let me know and I will get it implemented.

**Comment by chigkim** [comment]
Looking at the docs, I'm not exactly sure what relationship it supports.

https://developer.apple.com/documentation/applemusicapi/get_a_catalog_genre_s_relationship_directly_by_name

However, would this do what I want? Something like this?

|https://api.music.apple.com/v1/catalog/us/genres/14/playlits |
